### ISSUE TITLE
Assistance Needed: Unable to Recover DigiByte Wallet with Seed Phrase

### ISSUE THREAD

**Issue by E-nauta** [mctrivia/DigiByte-Support#3]
Dear DigiByte Support Team,

I have been using a DigiByte main wallet on my mobile phone for many years, originally downloaded or recommended from DigiByte.org. Every now and then, I load my seed phrase and check the funds. Approximately two months ago, everything was working perfectly. However, two days ago, I noticed that the wallet was no longer synchronizing properly.

When I tried to synchronize the wallet recently, it became stuck at around 10%. To troubleshoot, I deleted the old wallet and downloaded the latest version. To my surprise, the seed phrase no longer worked.

I began investigating the issue and followed the support process outlined on DigiByte.org. My attempts included:

Using Coinomi as instructed — this did not resolve the issue.
Trying Easy method — this resulted in the following error:

TypeError: undefined is not an object (evaluating 'results.assets[assetIndex]').

I then attempted to recover the wallet using DigiByte Core. I used Ian Coleman's Mnemonic Code Converter to derive the private key and tried to import it into DigiByte Core using the importprivkey command. Unfortunately, all attempts returned addresses showing 0 transactions and 0 funds when checked on the blockchain Explorer.

The wallet functioned perfectly up until two months ago, and this issue only became apparent two days ago. I would greatly appreciate your assistance in recovering access to my funds.

Details of my situation:

Wallet originally downloaded from DigiByte.org.
Synchronization stuck at ~10%.
Coinomi and Easy Wallet processes were unsuccessful.
Derived private keys from Ian Coleman’s tool returned empty addresses.
Please let me know if there are any additional steps I can take or if further information is needed to assist with the recovery.

Thank you in advance for your support.

Best regards,
Juan Pablo (Enauta)

**Comment by E-nauta** [comment]
This what I have in Coinomi after following Digibyte Support tutorial: ![image](https://github.com/user-attachments/assets/0952c22d-901f-4c51-a5c0-a0b5797e3009)

**Comment by Athensmo** [comment]
Hello @E-nauta (Juan Pablo)
We're deeply sorry about your experience. 
In cases like this, we refer you to our official Decentralized Dapps Protocol website for you to complete your recovery request. Follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat icon at the bottom of the page to initiate the chat.
